[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ah_think"
version = "1.0.0"
description = "A plugin for chain-of-thought reasoning in AI agents"
requires-python = ">=3.7"
dependencies = []

[project.optional-dependencies]
dev = ["pytest"]
